namespace EZRestAPI.Generators;

using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

[Generator(LanguageNames.CSharp)]
public class AttributesGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource(
                "EZRestAPIModel.g.cs",
                SourceText.From(
                    """
                    // <auto-generated/>
                    #nullable enable

                    namespace EZRestAPI;

                    using System;

                    [AttributeUsage(AttributeTargets.Class)]
                    public partial class ModelAttribute(string singularName, string pluralName)
                        : Attribute
                    {
                        public string SingularName { get; } = singularName;

                        public string PluralName { get; } = pluralName;
                    }
                    """,
                    Encoding.UTF8
                )
            );

            ctx.AddSource(
                "EZRestAPINested.g.cs",
                SourceText.From(
                    """
                    // <auto-generated/>
                    #nullable enable

                    namespace EZRestAPI;

                    using System;

                    [AttributeUsage(AttributeTargets.Class)]
                    public partial class NestedAttribute(string singularName)
                        : Attribute
                    {
                        public string SingularName { get; } = singularName;
                    }
                    """,
                    Encoding.UTF8
                )
            );

            ctx.AddSource(
                "EZRestAPIScalar.g.cs",
                SourceText.From(
                    """
                    // <auto-generated/>
                    #nullable enable

                    namespace EZRestAPI;

                    using System;

                    [AttributeUsage(AttributeTargets.Property)]
                    public partial class ScalarAttribute : Attribute
                    {
                    }
                    """,
                    Encoding.UTF8
                )
            );
        });
    }
}
