namespace EZRestAPI.Generators;

using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

[Generator(LanguageNames.CSharp)]
public class AttributesGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource(
                "EZRestAPIEndpoints.g.cs",
                SourceText.From(
                    """
                    // <auto-generated/>
                    #nullable enable

                    namespace EZRestAPI;

                    using System;

                    /// <summary>
                    /// Selects which endpoints EZRestAPI generates for a [Model].
                    /// Exposure is opt-in: the default is <see cref="None"/>, which
                    /// registers the model in the DbContext and generates nothing else.
                    /// </summary>
                    [Flags]
                    public enum Endpoints
                    {
                        None = 0,
                        List = 1,
                        Create = 2,
                        Read = 4,
                        Update = 8,
                        Delete = 16,
                        Nested = 32,

                        Crud = List | Create | Read | Update | Delete,
                        ReadOnly = List | Read | Nested,
                        All = Crud | Nested,
                    }
                    """,
                    Encoding.UTF8
                )
            );

            ctx.AddSource(
                "EZRestAPIModel.g.cs",
                SourceText.From(
                    """
                    // <auto-generated/>
                    #nullable enable

                    namespace EZRestAPI;

                    using System;

                    [AttributeUsage(AttributeTargets.Class)]
                    public partial class ModelAttribute(string singularName, string pluralName)
                        : Attribute
                    {
                        public string SingularName { get; } = singularName;

                        public string PluralName { get; } = pluralName;

                        /// <summary>
                        /// Which endpoints to generate. Defaults to
                        /// <see cref="Endpoints.None"/>: DbContext registration only.
                        /// </summary>
                        public Endpoints Endpoints { get; set; }
                    }
                    """,
                    Encoding.UTF8
                )
            );

            ctx.AddSource(
                "EZRestAPINested.g.cs",
                SourceText.From(
                    """
                    // <auto-generated/>
                    #nullable enable

                    namespace EZRestAPI;

                    using System;

                    [AttributeUsage(AttributeTargets.Class)]
                    public partial class NestedAttribute(string singularName)
                        : Attribute
                    {
                        public string SingularName { get; } = singularName;
                    }
                    """,
                    Encoding.UTF8
                )
            );

            ctx.AddSource(
                "EZRestAPIScalar.g.cs",
                SourceText.From(
                    """
                    // <auto-generated/>
                    #nullable enable

                    namespace EZRestAPI;

                    using System;

                    [AttributeUsage(AttributeTargets.Property)]
                    public partial class ScalarAttribute : Attribute
                    {
                    }
                    """,
                    Encoding.UTF8
                )
            );
        });
    }
}
