namespace EZRestAPI.Generators;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

[Generator(LanguageNames.CSharp)]
public class AttributesGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource(
                "EZRestAPIModel.g.cs",
                SourceText.From("""
                    // <auto-generated/>
                    #nullable enable

                    namespace EZRestAPI;

                    [AttributeUsage(AttributeTargets.Class)]
                    public partial class ModelAttribute(string singularName, string pluralName)
                        : Attribute
                    {
                        public string SingularName { get; } = singularName;

                        public string PluralName { get; } = pluralName;
                    }
                    """, Encoding.UTF8));
        });
    }
}
