namespace EZRestAPI.Tests;

using System.Text;
using EZRestAPI.Providers;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

/// <summary>
/// Test-only generator: dumps the resolved <see cref="ProviderExtensions.Aggregate"/>
/// models as structured comment lines so fast tests can assert on the aggregate
/// provider (read properties, factory, commands) before any aggregate codegen
/// generator exists to observe it through.
/// </summary>
[Generator(LanguageNames.CSharp)]
public class AggregateProbeGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var aggregates = context.SyntaxProvider.GetAggregates().Collect();

        context.RegisterSourceOutput(
            aggregates,
            (ctx, items) =>
            {
                var builder = new StringBuilder();
                builder.AppendLine("// <auto-generated/>");

                foreach (var aggregate in items)
                {
                    builder.AppendLine(
                        $"// AGGREGATE {aggregate.SingularName} {aggregate.PluralName}"
                    );

                    foreach (var property in aggregate.Properties)
                    {
                        builder.AppendLine(
                            $"// PROPERTY {property.PropertyName} : {property.DtoTypeName}"
                        );
                    }

                    if (aggregate.Factory is { } factory)
                    {
                        builder.AppendLine($"// FACTORY {factory.Kind} {factory.Name}");
                        foreach (var parameter in factory.Parameters)
                        {
                            builder.AppendLine(
                                $"// FACTORY_PARAM {parameter.ParameterName} : {parameter.TypeName} : {parameter.Kind} : {parameter.Nested?.SingularName ?? "-"}"
                            );
                        }
                    }
                    else
                    {
                        builder.AppendLine("// NOFACTORY");
                    }

                    foreach (var command in aggregate.Commands)
                    {
                        builder.AppendLine($"// COMMAND {command.RouteName} {command.MethodName}");
                        foreach (var parameter in command.Parameters)
                        {
                            builder.AppendLine(
                                $"// COMMAND_PARAM {command.MethodName} {parameter.ParameterName} : {parameter.TypeName}"
                            );
                        }
                    }
                }

                ctx.AddSource(
                    "AggregateProbe.g.cs",
                    SourceText.From(builder.ToString(), Encoding.UTF8)
                );
            }
        );
    }
}
