namespace EZRestAPI.Utils;

using System.CodeDom.Compiler;

public static class SourceWriter
{
    /// <summary>
    /// Creates a writer preloaded with the headers every generated file needs:
    /// the auto-generated marker and an explicit nullable context.
    /// </summary>
    public static IndentedTextWriter Create()
    {
        var writer = new IndentedTextWriter(new StringWriter());

        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine("#nullable enable");
        writer.WriteLine();

        return writer;
    }
}
